// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateThing(ctx context.Context, arg CreateThingParams) (Thing, error)
	DeleteThing(ctx context.Context, id int64) error
	GetThing(ctx context.Context, id int64) (Thing, error)
	ListThings(ctx context.Context, arg ListThingsParams) ([]Thing, error)
	UpdateThing(ctx context.Context, arg UpdateThingParams) (Thing, error)
}

var _ Querier = (*Queries)(nil)
