// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: things.sql

package store

import (
	"context"
)

const createThing = `-- name: CreateThing :one
INSERT INTO things (name, description)
VALUES ($1, $2)
RETURNING id, name, description, create_time, update_time
`

type CreateThingParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) (Thing, error) {
	row := q.db.QueryRow(ctx, createThing, arg.Name, arg.Description)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const deleteThing = `-- name: DeleteThing :exec
DELETE FROM things WHERE id = $1
`

func (q *Queries) DeleteThing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteThing, id)
	return err
}

const getThing = `-- name: GetThing :one
SELECT id, name, description, create_time, update_time FROM things WHERE id = $1
`

func (q *Queries) GetThing(ctx context.Context, id int64) (Thing, error) {
	row := q.db.QueryRow(ctx, getThing, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listThings = `-- name: ListThings :many
SELECT id, name, description, create_time, update_time FROM things
ORDER BY update_time DESC
LIMIT $1 OFFSET $2
`

type ListThingsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListThings(ctx context.Context, arg ListThingsParams) ([]Thing, error) {
	rows, err := q.db.Query(ctx, listThings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thing
	for rows.Next() {
		var i Thing
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThing = `-- name: UpdateThing :one
UPDATE things
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description, create_time, update_time
`

type UpdateThingParams struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpdateThing(ctx context.Context, arg UpdateThingParams) (Thing, error) {
	row := q.db.QueryRow(ctx, updateThing, arg.ID, arg.Name, arg.Description)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}
